AWSTemplateFormatVersion: 2010-09-09
Description: 'BFHD Microservice stack'

Parameters:
  ProjectName:
    Type: String
    Description: 'Usually pn can be pnXYZ where XYZ are the feature number, useful to create
      experimental environments without crash official development environment'

  AlarmSNSTopicArn:
    Type: String
    Description: ARN of alarm topic

  BoApiDnsName:
    Type: String
    Description: 'The DNS name used for WEB rest API.'
  
  CorsAllowedDomains:
    Type: String
    Description: 'Comma separated list of domains allowed to make cross origin request'

  TemplateBucketBaseUrl:
    Type: String
    Description: 'The S3 bucket from which to fetch the templates used by this stack.'

  SubnetsIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: "subnets ids comma separated list. Where to deploy the microservice"
     
  SandboxSafeStorageBaseUrl:
    Type: String
    Description: 'Url to the SafeStorage microservice'

  VpcId:
    Type: String
    Description: 'VpcId where the microservice is going to be deployed'
  
  ApplicationLoadBalancerDomain:
    Type: String
    Description: 'Base URL of the load balancer where the service is going to be reachable'

  NetworkLoadBalancerLink:
    Type: String
    Description: 'network load balancer link for API-GW'
  
  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Kinesis stream that receive logs'
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  NotificationWrapperLambdaName:
    Type: String
    Description: 'The name of the lambda function used as wrapper for notification'
    
  NotificationWrapperLambdaTimeout:
    Type: Number
    Default: 30 
    
  NotificationWrapperLambdaMemorySize:
    Type: Number
    Default: 128

  LambdasBucketName:
    Type: String
    Description: 'The name of the S3 bucket where lambda code is stored'
    
  BucketBasePath:
    Type: String
    Description: 'The base path inside the S3 bucket where lambda code and other resources are stored'
    
  BfhdWafRequestLimit:
    Type: Number
    Default: "1000" # requests per 5 minutes
    
  EnhancedWebSecurityEnabled:
    Type: String
    AllowedValues:
      - "true"
      - "false"
    Description: 'Enable enhanced web security features in WAF'
    Default: "true"

  NotificationWrapperLambdaAllowedOrigin:
    Type: String
    Description: 'Comma separated list of websites allowed to use SEND back-ends API'

Resources:

 # lambda per lollipop playground
  BfhdAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-expose-service-openapi.yaml"
      Parameters:
        MicroServiceUniqueName: !Sub "${ProjectName}-bfhd"
        IntendedUsage: BACKOFFICE
        DnsName: !Ref BoApiDnsName
        ProjectName: !Ref ProjectName
        ServiceApiPath: "bfhd"
        NetworkLoadBalancerLink: !Ref NetworkLoadBalancerLink
        ApplicationLoadBalancerDomain: !Ref ApplicationLoadBalancerDomain
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        CloudwatchLogKinesisStreamArn: !Ref LogsKinesisSourceStreamArn
        OpenApiBucketName: !Ref LambdasBucketName
        OpenApiBucketKey: !Sub ${BucketBasePath}/docs/openapi/aws/api-bfhd-BO-aws.yaml

  BfhdWafAcl:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-waf-acl.yaml"
      Parameters:
        WAFName: !Sub "${ProjectName}-bfhd"
        IntendedUsage: BACKOFFICE
        APIGatewayARNs: !GetAtt BfhdAPI.Outputs.APIGatewayARN
        Limit: !Ref BfhdWafRequestLimit
        EnhancedWebSecurityEnabled: !Ref EnhancedWebSecurityEnabled
        # AllowedCidrs: !Ref IOBackendCidrs

  NotificationWrapperLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref NotificationWrapperLambdaName
      Runtime: nodejs22.x
      Handler: "index.handler"
      Code:
        S3Bucket: !Ref LambdasBucketName
        S3Key: !Sub "${BucketBasePath}/pn-notificationWrapper.zip"
      Role: !GetAtt NotificationWrapperLambdaRole.Arn
      Timeout: !Ref NotificationWrapperLambdaTimeout
      MemorySize: !Ref NotificationWrapperLambdaMemorySize
      Environment:
        Variables:
          CORS_ALLOWED_DOMAINS: !Ref CorsAllowedDomains
          APPLICATION_LOAD_BALANCER_DOMAIN: !Ref ApplicationLoadBalancerDomain
          NOTIFICATION_WRAPPER_ALLOWED_ORIGINS: !Ref NotificationWrapperLambdaAllowedOrigin
          #inserendo questo parametro posso chiamare delivery senza riautenticarmi lato codice, perché sono autenticato giá su loadbalancer
          SAFE_STORAGE: !Ref SandboxSafeStorageBaseUrl
          #inserire qui
      VpcConfig:
        SecurityGroupIds:
          - !GetAtt HelpdeskLambdaVpcSecurityGroup.GroupId
        SubnetIds: !Ref SubnetsIds
      TracingConfig:
        Mode: Active

  HelpdeskLambdaVpcSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub Security Group for ${ProjectName}-notificationWrapper Lambda function
      VpcId: !Ref VpcId

  NotificationWrapperLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-notificationWrapperLambdaRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole

  # Lambda access right
  NotificationWrapperLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref NotificationWrapperLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*"


  NotificationWrapperLambdaAlarms:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/lambda-alarms.yaml"
      Parameters:
        FunctionName: !Ref NotificationWrapperLambda
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
